[package]
name = "uniswap-v3-mvp"
version = "0.1.0"
edition = "2021"

[lib]
name = "uniswap_v3_mvp"
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5"
substreams-ethereum = "0.9"
prost = "0.11"
prost-types = "0.11"

[build-dependencies]
substreams-ethereum = "0.9"
prost-build = "0.11"